### ISSUE TITLE
Mobile Version of these skills

### ISSUE THREAD

**Issue by saiweb** [microsoft/WindowsVisionSkillsPreview#22]
It would be nice if you can provide the NuGet packages that are compatible with .NET Standard 2.0, iOS and Android along with UWP. That way we could AI Vision apps for the mobile platforms. After all, mobile is nothing without cloud support, and cloud needs mobile frontend in addition to desktop, web, etc.

**Comment by LPBourret** [comment]
> It would be nice if you can provide the NuGet packages that are compatible with .NET Standard 2.0, iOS and Android along with UWP. That way we could AI Vision apps for the mobile platforms. After all, mobile is nothing without cloud support, and cloud needs mobile frontend in addition to desktop, web, etc.

Hi saiweb,
We have plans to release .NetCore 3.0 and Win32 app compatibility with all our skills in the very near future. However at this time we don't have plans for iOS or Android support in the cards. 
To be clear, the set of Windows Vision Skills we released run locally on the Windows device the app ingesting them is installed, so no cloud registration or internet connectivity is needed.
