### ISSUE TITLE
Data Error (Cyclic Redundancy Check)" 

### ISSUE THREAD

**Issue by vc815** [microsoft/WindowsVisionSkillsPreview#27]
hi,    i run the projrct of ObjectDetectorSample  .error : Data Error (Cyclic Redundancy Check)" 
run location "  await InitializeObjectDetectorAsync();"

how  fix this 
thanks!

**Comment by LPBourret** [comment]
Hi,
I have not seen this issue before, are you running on Windows build 17763+ on a x64 machine?
Can you pin-point the line that throws this exception? CyclicRedundancyCheck could be due to an unknown issue at Skill instantiation time but we would need more details

**Comment by LPBourret** [comment]
closing per no reply, feel free to reopen
