### ISSUE TITLE
Could not find Windows Runtime type 'Microsoft.AI.Skills.SkillInterfacePreview.ISkill'

### ISSUE THREAD

**Issue by fox1989** [microsoft/WindowsVisionSkillsPreview#40]
i loaded this lib on NuGet

**Comment by LPBourret** [comment]
> i loaded this lib on NuGet

Hi,
This error would indicate the interface cannot be found in the set of dependencies added to your project.
Could you elaborate a bit on your development environment (Visual Studio, Windows version) and project (Universal Windows App, .NetCore 3.0, C++/Winrt app, etc.).

**Comment by LPBourret** [comment]
closing per no reply, feel free to reopen

**Comment by saurabhdhole** [comment]
I to get rid of this issue.
"Could not find Windows Runtime type 'Microsoft.AI.Skills.SkillInterfacePreview.ISkill"
