### ISSUE TITLE
SkeletalDetectorSample_UWP Can not find any bodies in GPU mode

### ISSUE THREAD

**Issue by husthzy** [microsoft/WindowsVisionSkillsPreview#52]
The SkeletalDetectorSample_UWP can not find any bodies in GPU mode, but it runs correct in CPU mode. The ObjectDetectorSample_UWP runs correct both.

Environment:
Lonovo Y7000
Windows 10 Insider Preview Build 18965.rs_prerelease.190803
CPU: i7-9750H
RAM:16GB
GPU: Nvidia RTX 2060
IDE: Visual Studio 2019 community

**Comment by LPBourret** [comment]
Thank you, we are aware of a discrepancy in results when running on CPU compared to GPU with this skill and are investigating the root cause. I will update this thread once we provide a fix.

**Comment by husthzy** [comment]
Yes, It has been fixed. Thanks!
