### ISSUE TITLE
SkelectalDetector and Hand recognize

### ISSUE THREAD

**Issue by Kartijno** [microsoft/WindowsVisionSkillsPreview#54]
Hello,

Hand Recognize is not implemented?
Fabio

**Comment by Kartijno** [comment]
Hi!

I need recognize hand (left and Right) not every single finger. Two more question: this Skill is compatible with XBOX ? and last, if i use Vision Skill for commercial purpose , when and if you ll release final version it can be compatibility broken?

**Comment by Kartijno** [comment]
Ok perfect! If i understood well also Xbox is compatible with vision skill right? Thanks Ciao
F

**Comment by Kartijno** [comment]
I tested on Xbox but when I call create skill method async (in your skeletal yep sample) it crash with access violation exception

**Comment by LPBourret** [comment]
Closing this issue and following-up the XBox compat issue in the other thread (#55)
