### ISSUE TITLE
1.0.0.2 Intel Vision Skills NuGet Packages Broken / Attribution Text Files marked as 'Compile'

### ISSUE THREAD

**Issue by mobilewares** [microsoft/WindowsVisionSkillsPreview#62]
FYI: 
There's a problem with the 1.0.0.2 'Intel' Vision Skills packages that were published by Intel. (not yet tried to see if the 1.0.0.3 updates suffer same problem).

All the embedded attibution 'text' files appear to have been included with the 'Compile' build action - which prevents any samples from being built once you download the packages from NuGet. (VS2019 throws a bunch of compile errors as it tries to treach all these text files as code).

To fix this I had to go into the NuGet package cache folder and manually delete all the .txt files from those subfolders before I could compile anything.

As per above - just saw 1.0.03 has just been published (with new skills) - will check to see if it's still a problem there (can't find any release notes for your stuff so I'm unable to see what was fixed).

thanks
Niall

**Comment by LPBourret** [comment]
The issue was addressed in the new version of Intel's NuGet packages already published and there should be a new version of their samples available shortly. In the meantime simply update the NuGet package to the newer version

**Comment by mobilewares** [comment]
Thanks - I guess I need to manually clear old version from my NuGet package cache as just directly updating to 1.0.3.0 doesn't seem to have fixed the issue.  Looking forward to seeing the new samples being published - hopefully Intel can do better job of keeping it in sync with NuGet releases (1.0.3.0 binaries now nearly a week old and samples still at 1.0.2.0).  It would be a lot better if their samples could just be placed on GitHub repo so we can provide feedback too if needed (and going through their sign in system each time to get .zip file is a pitb).

**Comment by LPBourret** [comment]
Hi,
I agree, we suggested this as well earlier and to my knowledge this is in the work :). I will relay your feedback to Intel devs to reinforce the benefit of going through GitHub. Thx for trying it out and we appreciate any additional feedback

**Comment by mobilewares** [comment]
Some Addition Feedback  8)
1) Please ask them to add GPU Learning Device Model support - their stuff is quite slow without it - I think all their skills are CPU only right now.
2) Also - the amount of redistributables for their Skills is too large - they aren't models (which would be acceptable as it would be more comprehensive training data resulting in better Skill). It seems to just be supporting library dll's. I think there's something like 170mb of extra files just for a single Skill of theirs (not sure if they all share same ones) - which gets quite unmanageable for redistributing the App. So ask them to please try to get some lightweight version of this - these skills can't possibly need everything that's in those DLL's.

3) Also feedback for the Microsoft Vision Skills : the ObjectDetectorPreview is awesome - so much better than what we can produce in Custom Vision. One issue though is also the file size (model is 340Mb) - which again means each new version of our app is this much larger. Is there any way you to provide (in future release) a way to decouple the NuGet package from the model so it can be supplied via code when initialized (like the CV API does - ability to take an IStorageFile or Uri as model source). Our App is able to work with models downloaded into the Application Storage folders (for CV Models) - which makes redistribution of updates so much easier (smaller).

**Comment by LPBourret** [comment]
@mobilewares Intel GitHub: https://github.com/intel/Intel-AI-Skills

I'll reply to your feedback soon

**Comment by LPBourret** [comment]
Hi again,
1) For Intel Windows skills, I believe Intel integrated GPUs (Iris, Intel HD, etc.) are supported but not GPUs from other manufacturers for the moment. I did pass along that feedback for supporting other GPUs
2) I'll relay this feedback to Intel in our next meeting, app footprint is indeed important.
3) Glad you like the results you get from the object detector, indeed the model is big but note that if you distribute your app through the store, only differential updates are pulled in (not the whole app assets if unchanged at every update) see [this blog entry](https://blogs.msdn.microsoft.com/appinstaller/2016/12/03/differential-updates-for-uwp-apps/)
We could thinker around passing specified model files but we have to take into consideration why we do it this way for now as well (encrypt the model to avoid tempering, need to be usable offline, etc.)
