### ISSUE TITLE
Output ObjectDetectorPreview Confidence Level with Matches

### ISSUE THREAD

**Issue by mobilewares** [microsoft/WindowsVisionSkillsPreview#64]
Request for ObjectDetectorPreview : 
Is it possible to output the confidence level with each match - like what is returned for Windows ML / Custom Vision ONNX files? The Evaluations are returning some poor results in some cases (ie. mixing up leaves on a tree branch as a 'Person' from a 4k security camera is one ongoing issue) - I'm pretty sure ability to filter out low confidence matches would make a big difference here.

**Comment by LPBourret** [comment]
Thank you for the feedback, let me thinker on this. We do filter out low probabilities before exposing the results. In this case, the leaves may have a person-like shape, which is hard to discern, but I agree that exposing the confidence could help at least debug this issue. We could also expose the confidence threshold we use to filter out results as an optional input parameter that you can set (i.e. only report very high confidence results).

**Comment by LPBourret** [comment]
Hi @mobilewares 
please take a look at the new release of the [*ObjectDetector* Windows Skill nuget package](https://www.nuget.org/packages/Microsoft.AI.Skills.Vision.ObjectDetectorPreview/) that exposes 2 new input features for you to filter both by type of object and by the confidence reported, This confidence is also now newly reported by the *ObjectDetectorResult* class.

**Comment by mobilewares** [comment]
Thanks for adding these features - much appreciated. I will have a play in next couple of days and see if it can help improve results (either way, having the confidence coming back was also on our wish list for other projects).

**Comment by mobilewares** [comment]
Hi,

I just tried out the updated sample app & it appears the invalid object detection matches are returning very high confidence - hence filtering out based on confidence is not going to work in this specific case unfortunately.  

I'm guessing this would likely indicate a problem with the model (rather than the code/library) - see excerpt below (from security camera) - it's 95.6% convinced that this tree is a person.

![image](https://user-images.githubusercontent.com/4155775/70836820-9d664480-1e55-11ea-854d-94a139096c12.png)

thanks
Niall
